### ISSUE TITLE
Detect an error if bin size exceeds the size limit

### ISSUE THREAD

**Issue by ghostdevv** [ghostdevv/sourcebin#13]

**Comment by DaisyDogs07** [comment]
You're the owner, You don't need to open an issue to add a feature

**Comment by ghostdevv** [comment]
@DaisyDogs07 It's for organisation / reminding me to actually do it

**Comment by DaisyDogs07** [comment]
@ghostdevv Would you like a notepad for that?

**Comment by ghostdevv** [comment]
@DaisyDogs07 na xd

**Comment by DaisyDogs07** [comment]
ok

**Comment by ghostdevv** [comment]
closing this, doing investigation in this came up with too many problems
